### ISSUE TITLE
having overlapping menues, not able to manipulate graph

### ISSUE THREAD

**Issue by rescuehero** [cytoscape/cytoscape#18]
hey guys,

I tried to use cytoscape to connect to a neo4j database and view/edit it.
Problem is, that as soon as I loaded the graph into cytoscape, no matter if I use:
-.graphml file
-stream with neo4j plugin
-stream with cyNeo4j

cytoscape will overlap all the menus,
just like the png attached shows.

![cytoerror](https://user-images.githubusercontent.com/11653204/36278516-6469c82e-1294-11e8-99cb-15c01e4b92e0.png)

**Comment by AlexanderPico** [comment]
Wow. That screenshot is a mess, indeed.  I'm not sure I understand what I'm looking at...  If you launch Cytoscape from the command line, e.g, ./cytoscape.sh from the installation dir, then perhaps you could provide a stacktrace of errors thrown by Cytoscape?

Otherwise, you might contact the neo4J app authors who can attempt to reproduce and identify the source of the error: http://apps.cytoscape.org/apps/cyneo4j

**Comment by rescuehero** [comment]
@AlexanderPico  reinstalling the application fixed the problem for now. I am going to create a new issue if it happens again and will instantly post a stacktrace to it.

Thanks for your reply
